### ISSUE TITLE
file_root/neutron/ml2.sls - is vxlan section correct? -  

### ISSUE THREAD

**Issue by rtmie** [cloudbase/salt-openstack#10]
vni_ranges looks like cut and paste from previous gre section. 
If I want to configure vxlan in my pilar how should it look, if is add tunnel_start and tunnel_end will they get mapped to vni_ranges in the config file. Also can I set vxlan_group?

**Comment by ionutbalutoiu** [comment]
Tunneling support for VXLAN and GRE was added in a recent commit.
For VXLAN tunneling, you must define your configuration parameters in [network_resources.sls](https://github.com/cloudbase/salt-openstack/blob/master/pillar_root/default_template/network_resources.sls#L36-L50) file from pillar_root.
Documentation on how to do this is added on the README at [section 2.3](https://github.com/cloudbase/salt-openstack#23-edit-network_resourcessls-file).
