### ISSUE TITLE
Cloning instruction needs correction

### ISSUE THREAD

**Issue by blsaws** [cloudbase/salt-openstack#11]
In README.md,

To "Clone the salt-openstack cloudbase repository:"

"git clone git@github.com:cloudbase/salt-openstack.git" should be replaced with
"git clone https://github.com/cloudbase/salt-openstack.git"

As this is what I get with the original instruction:
bryan@zzz:~$ git clone git@github.com:cloudbase/salt-openstack.git
Cloning into 'salt-openstack'...
The authenticity of host 'github.com (192.30.252.129)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.129' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by ociuhandu** [comment]
Updated readme file
