### ISSUE TITLE
The examples are needed

### ISSUE THREAD

**Issue by heww** [cloudbase/salt-openstack#7]
The examples are needed for cloudbase/salt-openstack like examples of puppetlabs-openstack https://github.com/puppetlabs/puppetlabs-openstack/tree/master/examples

**Comment by ociuhandu** [comment]
Hello, we're working on adding some example configurations, we will let you know once they are available.

**Comment by UtahDave** [comment]
+1

Yeah, I'd love to see a simple example configuration.

I'd be willing to test, if that would be helpful.

**Comment by ibenrodriguez** [comment]
BTW - there are some reference to this SaltStack for OpenStack work mentioned on the OPNFV wiki here: https://wiki.opnfv.org/salt4nfv

**Comment by chekolyn** [comment]
I've been working on setting up a Vagrant Dev enviroment for rapid prototyping; is not ready yet but just letting you know. 

We can create different scenarios under the vagrant subfolder each with it's own pillar_data  matching the Vagrantfile. 
https://github.com/chekolyn/salt-openstack/commits/vagrant

This is based on the work done at https://github.com/komljen/ceph-salt

**Comment by chekolyn** [comment]
Hey Guys,

I've made a couple of example in a Vagrant dev environment, but I only got allinone working.
Here's the link https://github.com/chekolyn/salt-openstack/tree/vagrant/vagrant

**Comment by ionutbalutoiu** [comment]
Hello! Sample pillar configurations were added in a recent commit. You can find them [here](https://github.com/cloudbase/salt-openstack/tree/master/pillar_root/samples).
